//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCarpetsService.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Widths = new HashSet<Width>();
        }
    
        public int Id { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> RangeId { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public int ColourId { get; set; }
        public int MaterialId { get; set; }
        public int StyleId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Lookup MaterialsLookup { get; set; }
        public virtual Lookup ColoursLookup { get; set; }
        public virtual Lookup StylesLookup { get; set; }
        public virtual Lookup TypesLookup { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Range Range { get; set; }
        public virtual ICollection<Width> Widths { get; set; }
    }
}
